runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /$
  static_files: index.html
  upload: index.html

- url: /help\.html$
  static_files: help.html
  upload: help.html

- url: /api
  script: bawgle.app

libraries:
- name: jinja2
  version: 2.6

skip_files:
- util/
- dict/
- .git/
